name: Test Status

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run all unit tests
        run: cargo test --verbose

      - name: run all example tests
        run: cargo test --all --examples
